kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
        - name: apache-ct
          image: httpd:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu:  100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 250Mi
